;<?php die('');?>
isWindows=
enableOldActionSelector=
use_error_handler=1
dbProfils="dbprofils.ini.php"
unusedModules=jacldb
trustedModules=
checkTrustedModules=
modulesPath="lib:jelix-modules/,app:modules/"
pluginsPath="app:plugins/"
timeZone="Europe/Paris"
theme=default
charset="UTF-8"
locale=en_EN
startAction="default:index"
startModule=jelix
[coordplugins]
[tplplugins]
defaultJformsBuilder=html
[responses]
html=myHtmlResponse
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xul=jResponseXul
xuloverlay=jResponseXulOverlay
xuldialog=jResponseXulDialog
xulpage=jResponseXulPage
rdf=jResponseRdf
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
ltx2pdf=jResponseLatexToPdf
tcpdf=jResponseTcpdf
soap=jResponseSoap
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
html.path="/var/www/helenekling/HeleneKling/responses/myHtmlResponse.class.php"
redirect.path="/var/www/helenekling/lib/jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="/var/www/helenekling/lib/jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="/var/www/helenekling/lib/jelix/core/response/jResponseBinary.class.php"
text.path="/var/www/helenekling/lib/jelix/core/response/jResponseText.class.php"
cmdline.path="/var/www/helenekling/lib/jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="/var/www/helenekling/lib/jelix/core/response/jResponseJsonrpc.class.php"
json.path="/var/www/helenekling/lib/jelix/core/response/jResponseJson.class.php"
xmlrpc.path="/var/www/helenekling/lib/jelix/core/response/jResponseXmlrpc.class.php"
xul.path="/var/www/helenekling/lib/jelix/core/response/jResponseXul.class.php"
xuloverlay.path="/var/www/helenekling/lib/jelix/core/response/jResponseXulOverlay.class.php"
xuldialog.path="/var/www/helenekling/lib/jelix/core/response/jResponseXulDialog.class.php"
xulpage.path="/var/www/helenekling/lib/jelix/core/response/jResponseXulPage.class.php"
rdf.path="/var/www/helenekling/lib/jelix/core/response/jResponseRdf.class.php"
xml.path="/var/www/helenekling/lib/jelix/core/response/jResponseXml.class.php"
zip.path="/var/www/helenekling/lib/jelix/core/response/jResponseZip.class.php"
rss2.0.path="/var/www/helenekling/lib/jelix/core/response/jResponseRss20.class.php"
atom1.0.path="/var/www/helenekling/lib/jelix/core/response/jResponseAtom10.class.php"
css.path="/var/www/helenekling/lib/jelix/core/response/jResponseCss.class.php"
ltx2pdf.path="/var/www/helenekling/lib/jelix/core/response/jResponseLatexToPdf.class.php"
tcpdf.path="/var/www/helenekling/lib/jelix/core/response/jResponseTcpdf.class.php"
soap.path="/var/www/helenekling/lib/jelix/core/response/jResponseSoap.class.php"
htmlfragment.path="/var/www/helenekling/lib/jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="/var/www/helenekling/lib/jelix/core/response/jResponseHtml.class.php"
[_coreResponses]
html=jResponseHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xul=jResponseXul
xuloverlay=jResponseXulOverlay
xuldialog=jResponseXulDialog
xulpage=jResponseXulPage
rdf=jResponseRdf
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
ltx2pdf=jResponseLatexToPdf
tcpdf=jResponseTcpdf
soap=jResponseSoap
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
html.path="/var/www/helenekling/lib/jelix/core/response/jResponseHtml.class.php"
redirect.path="/var/www/helenekling/lib/jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="/var/www/helenekling/lib/jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="/var/www/helenekling/lib/jelix/core/response/jResponseBinary.class.php"
text.path="/var/www/helenekling/lib/jelix/core/response/jResponseText.class.php"
cmdline.path="/var/www/helenekling/lib/jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="/var/www/helenekling/lib/jelix/core/response/jResponseJsonrpc.class.php"
json.path="/var/www/helenekling/lib/jelix/core/response/jResponseJson.class.php"
xmlrpc.path="/var/www/helenekling/lib/jelix/core/response/jResponseXmlrpc.class.php"
xul.path="/var/www/helenekling/lib/jelix/core/response/jResponseXul.class.php"
xuloverlay.path="/var/www/helenekling/lib/jelix/core/response/jResponseXulOverlay.class.php"
xuldialog.path="/var/www/helenekling/lib/jelix/core/response/jResponseXulDialog.class.php"
xulpage.path="/var/www/helenekling/lib/jelix/core/response/jResponseXulPage.class.php"
rdf.path="/var/www/helenekling/lib/jelix/core/response/jResponseRdf.class.php"
xml.path="/var/www/helenekling/lib/jelix/core/response/jResponseXml.class.php"
zip.path="/var/www/helenekling/lib/jelix/core/response/jResponseZip.class.php"
rss2.0.path="/var/www/helenekling/lib/jelix/core/response/jResponseRss20.class.php"
atom1.0.path="/var/www/helenekling/lib/jelix/core/response/jResponseAtom10.class.php"
css.path="/var/www/helenekling/lib/jelix/core/response/jResponseCss.class.php"
ltx2pdf.path="/var/www/helenekling/lib/jelix/core/response/jResponseLatexToPdf.class.php"
tcpdf.path="/var/www/helenekling/lib/jelix/core/response/jResponseTcpdf.class.php"
soap.path="/var/www/helenekling/lib/jelix/core/response/jResponseSoap.class.php"
htmlfragment.path="/var/www/helenekling/lib/jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="/var/www/helenekling/lib/jelix/core/response/jResponseHtml.class.php"
[error_handling]
messageLogFormat="%date%\t[%code%]\t%msg%\t%file%\t%line%\n"
logFile="error.log"
email="root@localhost"
emailHeaders="Content-Type: text/plain; charset=UTF-8\nFrom: webmaster@yoursite.com\nX-Mailer: Jelix\nX-Priority: 1 (Highest)\n"
quietMessage="Une erreur technique est survenue. Désolé pour ce désagrément."
showInFirebug=
default="ECHO EXIT"
error="ECHO EXIT"
warning=ECHO
notice=ECHO
strict=ECHO
exception=ECHO
[compilation]
checkCacheFiletime=1
force=
[urlengine]
engine=basic_significant
enableParser=1
multiview=
scriptNameServerVariable=SCRIPT_NAME
pathInfoInQueryParameter=
basePath="/"
jelixWWWPath="/jelix/"
defaultEntrypoint=index
entrypointExtension=".php"
notfoundAct=
simple_urlengine_https=
significantFile="urls.xml"
urlScript="jelix.php"
urlScriptPath="/"
urlScriptName="elix.php"
urlScriptId=elix
urlScriptIdenc=elix
[simple_urlengine_entrypoints]
index="@classic"
xmlrpc="@xmlrpc"
jsonrpc="@jsonrpc"
rdf="@rdf"
[basic_significant_urlengine_entrypoints]
index=1
xmlrpc=1
jsonrpc=1
rdf=1
[logfiles]
default="messages.log"
[mailer]
webmasterEmail="root@localhost"
webmasterName=
mailerType=mail
hostname=
sendmailPath="/usr/sbin/sendmail"
smtpHost=localhost
smtpPort=25
smtpSecure=
smtpHelo=
smtpAuth=
smtpUsername=
smtpPassword=
smtpTimeout=10
[acl]
driver=
[acl2]
driver=
[sessions]
start=1
shared_session=
name=
storage=
loadClasses=
[forms]
controls.datetime.input=menulists
controls.datetime.months.labels=names
datepicker=default
[datepickers]
default="jelix/js/jforms/datepickers/default/init.js"
[htmleditors]
default.engine.name=wymeditor
default.engine.file[]="jelix/jquery/jquery.js"
default.engine.file[]="jelix/wymeditor/jquery.wymeditor.js"
default.config="jelix/wymeditor/config/default.js"
default.skin.default="jelix/wymeditor/skins/default/screen.css"
[zones]
disableCache=
[classbindings]
[_allBasePath]
0="/var/www/helenekling/lib/jelix-modules/"
1="/var/www/helenekling/HeleneKling/modules/"
2="/var/www/helenekling/HeleneKling/plugins/tpl/"
3="/var/www/helenekling/HeleneKling/plugins/auth/"
4="/var/www/helenekling/HeleneKling/plugins/coord/"
5="/var/www/helenekling/HeleneKling/plugins/db/"
[_modulesPathList]
jelix="/var/www/helenekling/lib/jelix/core-modules/jelix/"
junittests="/var/www/helenekling/lib/jelix-modules/junittests/"
jWSDL="/var/www/helenekling/lib/jelix-modules/jWSDL/"
jacl2db="/var/www/helenekling/lib/jelix-modules/jacl2db/"
jauth="/var/www/helenekling/lib/jelix-modules/jauth/"
[_tplpluginsPathList_common]
0="/var/www/helenekling/lib/jelix/plugins/tpl/common/"
1="/var/www/helenekling/HeleneKling/plugins/tpl/common/"
[_tplpluginsPathList_html]
0="/var/www/helenekling/lib/jelix/plugins/tpl/html/"
1="/var/www/helenekling/HeleneKling/plugins/tpl/html/"
[_tplpluginsPathList_text]
0="/var/www/helenekling/lib/jelix/plugins/tpl/text/"
1="/var/www/helenekling/HeleneKling/plugins/tpl/text/"
[_tplpluginsPathList_xml]
0="/var/www/helenekling/lib/jelix/plugins/tpl/xml/"
[_tplpluginsPathList_ltx2pdf]
0="/var/www/helenekling/lib/jelix/plugins/tpl/ltx2pdf/"
[_tplpluginsPathList_xul]
0="/var/www/helenekling/lib/jelix/plugins/tpl/xul/"
[_pluginsPathList_acl2]
db="/var/www/helenekling/lib/jelix/plugins/acl2/db/"
[_pluginsPathList_auth]
class="/var/www/helenekling/lib/jelix/plugins/auth/class/"
ldap="/var/www/helenekling/lib/jelix/plugins/auth/ldap/"
db="/var/www/helenekling/lib/jelix/plugins/auth/db/"
lds="/var/www/helenekling/lib/jelix/plugins/auth/lds/"
[_pluginsPathList_jforms]
html="/var/www/helenekling/lib/jelix/plugins/jforms/html/"
htmllight="/var/www/helenekling/lib/jelix/plugins/jforms/htmllight/"
[_pluginsPathList_acl]
db="/var/www/helenekling/lib/jelix/plugins/acl/db/"
[_pluginsPathList_coord]
autolocale="/var/www/helenekling/lib/jelix/plugins/coord/autolocale/"
magicquotes="/var/www/helenekling/lib/jelix/plugins/coord/magicquotes/"
auth="/var/www/helenekling/lib/jelix/plugins/coord/auth/"
zendframework="/var/www/helenekling/lib/jelix/plugins/coord/zendframework/"
history="/var/www/helenekling/lib/jelix/plugins/coord/history/"
jacl="/var/www/helenekling/lib/jelix/plugins/coord/jacl/"
jacl2="/var/www/helenekling/lib/jelix/plugins/coord/jacl2/"
[_pluginsPathList_db]
pgsql="/var/www/helenekling/lib/jelix/plugins/db/pgsql/"
intuition="/var/www/helenekling/lib/jelix/plugins/db/intuition/"
mysql="/var/www/helenekling/lib/jelix/plugins/db/mysql/"
sqlite="/var/www/helenekling/lib/jelix/plugins/db/sqlite/"
oci="/var/www/helenekling/lib/jelix/plugins/db/oci/"
[_pluginsPathList_urls]
basic_significant="/var/www/helenekling/lib/jelix/plugins/urls/basic_significant/"
simple="/var/www/helenekling/lib/jelix/plugins/urls/simple/"
significant="/var/www/helenekling/lib/jelix/plugins/urls/significant/"
[_trustedModules]
0=jelix
1=junittests
2=jWSDL
3=jacl2db
4=jauth
