;<?php die('');?>
isWindows=
enableOldActionSelector=
use_error_handler=1
dbProfils="dbprofils.ini.php"
unusedModules=jacldb
trustedModules=
checkTrustedModules=
modulesPath="lib:jelix-modules/,app:modules/"
pluginsPath="lib:jelix-plugins/,app:plugins/"
timeZone="Europe/Paris"
theme=default
charset="UTF-8"
locale=en_EN
startAction="default:index"
startModule=HeleneKling
[coordplugins]
magicquotes=1
autolocale="autolocale.coord.ini.php"
enableUrlDetection=1
urlParamNameLanguage=lang
availableLanguageCode="fr_FR,en_EN"
auth="auth.coord.ini.php"
zendframework="zendframework.coord.ini.php"
[tplplugins]
defaultJformsBuilder=html
[responses]
html=myHtmlResponse
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xul=jResponseXul
xuloverlay=jResponseXulOverlay
xuldialog=jResponseXulDialog
xulpage=jResponseXulPage
rdf=jResponseRdf
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
ltx2pdf=jResponseLatexToPdf
tcpdf=jResponseTcpdf
soap=jResponseSoap
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
html.path="/homepages/5/d177360615/htdocs/HeleneKling/responses/myHtmlResponse.class.php"
redirect.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseBinary.class.php"
text.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseText.class.php"
cmdline.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseJsonrpc.class.php"
json.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseJson.class.php"
xmlrpc.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseXmlrpc.class.php"
xul.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseXul.class.php"
xuloverlay.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseXulOverlay.class.php"
xuldialog.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseXulDialog.class.php"
xulpage.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseXulPage.class.php"
rdf.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseRdf.class.php"
xml.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseXml.class.php"
zip.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseZip.class.php"
rss2.0.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseRss20.class.php"
atom1.0.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseAtom10.class.php"
css.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseCss.class.php"
ltx2pdf.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseLatexToPdf.class.php"
tcpdf.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseTcpdf.class.php"
soap.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseSoap.class.php"
htmlfragment.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseHtml.class.php"
[_coreResponses]
html=jResponseHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xul=jResponseXul
xuloverlay=jResponseXulOverlay
xuldialog=jResponseXulDialog
xulpage=jResponseXulPage
rdf=jResponseRdf
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
ltx2pdf=jResponseLatexToPdf
tcpdf=jResponseTcpdf
soap=jResponseSoap
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
html.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseHtml.class.php"
redirect.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseBinary.class.php"
text.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseText.class.php"
cmdline.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseJsonrpc.class.php"
json.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseJson.class.php"
xmlrpc.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseXmlrpc.class.php"
xul.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseXul.class.php"
xuloverlay.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseXulOverlay.class.php"
xuldialog.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseXulDialog.class.php"
xulpage.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseXulPage.class.php"
rdf.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseRdf.class.php"
xml.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseXml.class.php"
zip.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseZip.class.php"
rss2.0.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseRss20.class.php"
atom1.0.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseAtom10.class.php"
css.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseCss.class.php"
ltx2pdf.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseLatexToPdf.class.php"
tcpdf.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseTcpdf.class.php"
soap.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseSoap.class.php"
htmlfragment.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="/homepages/5/d177360615/htdocs/lib/jelix/core/response/jResponseHtml.class.php"
[error_handling]
messageLogFormat="%date%\t[%code%]\t%msg%\t%file%\t%line%\n"
logFile="error.log"
email="root@localhost"
emailHeaders="Content-Type: text/plain; charset=UTF-8\nFrom: webmaster@yoursite.com\nX-Mailer: Jelix\nX-Priority: 1 (Highest)\n"
quietMessage="Une erreur technique est survenue. Désolé pour ce désagrément."
showInFirebug=
default="ECHO EXIT"
error="ECHO EXIT"
warning=ECHO
notice=ECHO
strict=ECHO
exception=ECHO
[compilation]
checkCacheFiletime=1
force=
[urlengine]
engine=basic_significant
enableParser=1
multiview=
scriptNameServerVariable=ORIG_SCRIPT_NAME
pathInfoInQueryParameter=
basePath="/"
jelixWWWPath="/jelix/"
defaultEntrypoint=index
entrypointExtension=".php"
notfoundAct=
simple_urlengine_https=
significantFile="urls.xml"
urlScript="/index.php"
urlScriptPath="/"
urlScriptName="index.php"
urlScriptId=index
urlScriptIdenc=index
[simple_urlengine_entrypoints]
index="@classic"
xmlrpc="@xmlrpc"
jsonrpc="@jsonrpc"
rdf="@rdf"
[basic_significant_urlengine_entrypoints]
index=1
xmlrpc=1
jsonrpc=1
rdf=1
[logfiles]
default="messages.log"
[mailer]
webmasterEmail="helene_kling@yahoo.com"
webmasterName="Helene Kling"
mailerType=mail
hostname=
sendmailPath="/usr/sbin/sendmail"
smtpHost=localhost
smtpPort=25
smtpSecure=
smtpHelo=
smtpAuth=
smtpUsername=
smtpPassword=
smtpTimeout=10
[acl]
driver=
[acl2]
driver=
[sessions]
start=1
shared_session=
name=
storage=
loadClasses=
[forms]
controls.datetime.input=menulists
controls.datetime.months.labels=names
datepicker=default
[datepickers]
default="jelix/js/jforms/datepickers/default/init.js"
[htmleditors]
default.engine.name=wymeditor
default.engine.file[]="jelix/jquery/jquery.js"
default.engine.file[]="jelix/wymeditor/jquery.wymeditor.js"
default.config="jelix/wymeditor/config/default.js"
default.skin.default="jelix/wymeditor/skins/default/screen.css"
full.engine.name=tinymce
full.engine.file="tiny_mce/tiny_mce.js"
full.config="tiny_mce/tinymce_default.js"
[zones]
disableCache=
[classbindings]
[_allBasePath]
0="/homepages/5/d177360615/htdocs/lib/jelix-modules/"
1="/homepages/5/d177360615/htdocs/HeleneKling/modules/"
2="/homepages/5/d177360615/htdocs/HeleneKling/plugins/db/"
3="/homepages/5/d177360615/htdocs/HeleneKling/plugins/coord/"
4="/homepages/5/d177360615/htdocs/HeleneKling/plugins/auth/"
5="/homepages/5/d177360615/htdocs/HeleneKling/plugins/tpl/"
[_modulesPathList]
jelix="/homepages/5/d177360615/htdocs/lib/jelix/core-modules/jelix/"
jauth="/homepages/5/d177360615/htdocs/lib/jelix-modules/jauth/"
jacl2db="/homepages/5/d177360615/htdocs/lib/jelix-modules/jacl2db/"
jWSDL="/homepages/5/d177360615/htdocs/lib/jelix-modules/jWSDL/"
junittests="/homepages/5/d177360615/htdocs/lib/jelix-modules/junittests/"
events="/homepages/5/d177360615/htdocs/HeleneKling/modules/events/"
HeleneKling="/homepages/5/d177360615/htdocs/HeleneKling/modules/HeleneKling/"
jPicasa="/homepages/5/d177360615/htdocs/HeleneKling/modules/jPicasa/"
NewsLetter="/homepages/5/d177360615/htdocs/HeleneKling/modules/NewsLetter/"
widgets="/homepages/5/d177360615/htdocs/HeleneKling/modules/widgets/"
[_pluginsPathList_db]
intuition="/homepages/5/d177360615/htdocs/lib/jelix/plugins/db/intuition/"
mysql="/homepages/5/d177360615/htdocs/lib/jelix/plugins/db/mysql/"
sqlite="/homepages/5/d177360615/htdocs/lib/jelix/plugins/db/sqlite/"
oci="/homepages/5/d177360615/htdocs/lib/jelix/plugins/db/oci/"
pgsql="/homepages/5/d177360615/htdocs/lib/jelix/plugins/db/pgsql/"
[_pluginsPathList_auth]
class="/homepages/5/d177360615/htdocs/lib/jelix/plugins/auth/class/"
db="/homepages/5/d177360615/htdocs/lib/jelix/plugins/auth/db/"
ldap="/homepages/5/d177360615/htdocs/lib/jelix/plugins/auth/ldap/"
lds="/homepages/5/d177360615/htdocs/lib/jelix/plugins/auth/lds/"
[_pluginsPathList_acl]
db="/homepages/5/d177360615/htdocs/lib/jelix/plugins/acl/db/"
[_tplpluginsPathList_text]
0="/homepages/5/d177360615/htdocs/lib/jelix/plugins/tpl/text/"
1="/homepages/5/d177360615/htdocs/HeleneKling/plugins/tpl/text/"
[_tplpluginsPathList_common]
0="/homepages/5/d177360615/htdocs/lib/jelix/plugins/tpl/common/"
1="/homepages/5/d177360615/htdocs/HeleneKling/plugins/tpl/common/"
[_tplpluginsPathList_ltx2pdf]
0="/homepages/5/d177360615/htdocs/lib/jelix/plugins/tpl/ltx2pdf/"
[_tplpluginsPathList_html]
0="/homepages/5/d177360615/htdocs/lib/jelix/plugins/tpl/html/"
1="/homepages/5/d177360615/htdocs/HeleneKling/plugins/tpl/html/"
[_tplpluginsPathList_xul]
0="/homepages/5/d177360615/htdocs/lib/jelix/plugins/tpl/xul/"
[_tplpluginsPathList_xml]
0="/homepages/5/d177360615/htdocs/lib/jelix/plugins/tpl/xml/"
[_pluginsPathList_jforms]
htmllight="/homepages/5/d177360615/htdocs/lib/jelix/plugins/jforms/htmllight/"
html="/homepages/5/d177360615/htdocs/lib/jelix/plugins/jforms/html/"
[_pluginsPathList_acl2]
db="/homepages/5/d177360615/htdocs/lib/jelix/plugins/acl2/db/"
[_pluginsPathList_urls]
basic_significant="/homepages/5/d177360615/htdocs/lib/jelix/plugins/urls/basic_significant/"
significant="/homepages/5/d177360615/htdocs/lib/jelix/plugins/urls/significant/"
simple="/homepages/5/d177360615/htdocs/lib/jelix/plugins/urls/simple/"
[_pluginsPathList_coord]
jacl="/homepages/5/d177360615/htdocs/lib/jelix/plugins/coord/jacl/"
history="/homepages/5/d177360615/htdocs/lib/jelix/plugins/coord/history/"
auth="/homepages/5/d177360615/htdocs/lib/jelix/plugins/coord/auth/"
magicquotes="/homepages/5/d177360615/htdocs/lib/jelix/plugins/coord/magicquotes/"
zendframework="/homepages/5/d177360615/htdocs/HeleneKling/plugins/coord/zendframework/"
autolocale="/homepages/5/d177360615/htdocs/lib/jelix/plugins/coord/autolocale/"
jacl2="/homepages/5/d177360615/htdocs/lib/jelix/plugins/coord/jacl2/"
[_trustedModules]
0=jelix
1=jauth
2=jacl2db
3=jWSDL
4=junittests
5=events
6=HeleneKling
7=jPicasa
8=NewsLetter
9=widgets
